- name: Provisioning Deployment Server
  connection: ansible.netcommon.network_cli
  hosts: servers
  become: true
  tasks:
    - name: Saving Temporary Files
      become: true
      copy:
        src: /transfer/
        dest: /home/ubuntu/transfer/
        remote_src: false
        mode: 0600

    - name: Installing Initial System Packages
      apt:
        state: latest
        update_cache: yes
        upgrade: 'yes'

    - name: Rebooting System
      reboot:
        reboot_timeout: 120

    - name: Adding Docker GPG Apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Installing Additional Required Packages
      apt:
        pkg:
          - docker-ce
          - pip
          - haveged
        state: latest
        update_cache: yes
    
    - name: Installing Docker Compose Module
      pip:
        name: docker-compose
        state: latest

    - name: Cloning Repository
      git:
        repo: https://github.com/makchamp/bac.git
        dest: /home/ubuntu/bac
        version: master
    
    - name: Copying Client .ENV
      copy:
        src: /home/ubuntu/transfer/deployment/client.env
        dest: /home/ubuntu/bac/client/.env
        remote_src: true

    - name: Copying Server .ENV
      copy:
        src: /home/ubuntu/transfer/deployment/server.env
        dest: /home/ubuntu/bac/server/.env
        remote_src: true
    
    - name: Copying Docker .ENV
      copy:
        src: /home/ubuntu/transfer/deployment/docker.env
        dest: /home/ubuntu/bac/infrastructure/.env
        remote_src: true

    - name: Fixing Local Repository Permissions
      become: true
      file:
        path: /home/ubuntu/bac
        owner: ubuntu
        group: ubuntu

    - name: Opening Up Required Application Ports
      become: true
      shell:
        cmd: sudo bash /home/ubuntu/bac/infrastructure/deployment/PLaunch.sh
    
    - name: Restarting Docker Service
      become: true
      service:
        name: docker
        state: restarted
    
    - name: Launching Application
      become: true
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/bac/infrastructure/deployment
        files:
        - docker-compose.yml
        state: present