- name: Provisioning Deployment Server
  connection: ansible.netcommon.network_cli
  hosts: servers
  become: true
  tasks:
    - name: Saving Temporary Files
      become: true
      copy:
        src: /transfer/
        dest: /home/ubuntu/transfer/
        remote_src: false
        mode: 0600

    - name: Installing Initial System Packages
      apt:
        state: latest
        update_cache: yes
        upgrade: 'yes'

    - name: Rebooting System
      shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed' 
      args:
        removes: /var/run/reboot-required
      async: 300
      poll: 1
      ignore_errors: true
     
    - name: Waiting for Reconnection
      wait_for_connection:
        delay: 10
        timeout: 60

    - name: Adding Docker GPG Apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Installing Additional Required Packages
      apt:
        pkg:
          - docker-ce
          - pip
          - haveged
        state: latest
        update_cache: yes
    
    - name: Installing Docker Compose Module
      pip:
        name: docker-compose
        state: latest

    - name: Copying Private Key to SSH Directory
      copy:
        src: /home/ubuntu/transfer/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        remote_src: true
        mode: 0600

    - name: Cloning Repository
      git:
        repo: git@github.com:makchamp/bac.git
        dest: /home/ubuntu/bac
        key_file: /home/ubuntu/.ssh/id_rsa
        accept_hostkey: yes
        force: yes
        version: deployment
    
    - name: Copying Client .ENV
      copy:
        src: /home/ubuntu/transfer/client.env
        dest: /home/ubuntu/bac/client/.env
        remote_src: true

    - name: Copying Server .ENV
      copy:
        src: /home/ubuntu/transfer/server.env
        dest: /home/ubuntu/bac/server/.env
        remote_src: true
    
    - name: Copying Docker .ENV
      copy:
        src: /home/ubuntu/transfer/docker.env
        dest: /home/ubuntu/bac/infrastructure/.env
        remote_src: true

    - name: Fixing Local Repository Permissions
      become: true
      file:
        path: /home/ubuntu/bac
        owner: ubuntu
        group: ubuntu

    - name: Opening Up Required Application Ports
      become: true
      shell:
        cmd: sudo bash /home/ubuntu/bac/infrastructure/deployment/PLaunch.sh
    
    - name: Restarting Docker Service
      become: true
      service:
        name: docker
        state: restarted
    
    - name: Launching Application
      become: true
      community.docker.docker_compose:
        project_src: /home/ubuntu/bac/infrastructure/deployment
        files:
        - docker-compose.yml
        state: present