services:
  client:
    container_name: bac_client
    build:
      context: ../../client/
    ports:
      - "3001:3001"
    networks:
      - bac
  server:
    container_name: bac_server
    build:
      context: ../../server/
    ports:
      - "4000:4000"
    depends_on:
      - redis
    networks:
      - bac
  redis:
    container_name: bac_redis
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      bac:
        ipv4_address: 172.18.0.8

networks:
  bac:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1