services:
  client:
    container_name: bac_client
    build:
      context: ../../client/
    ports:
      - "3001:3001"
    networks:
      - bac
    volumes:
      - vol_client:/usr/src/scattegories/
  server:
    container_name: bac_server
    build:
      context: ../../server/
    ports:
      - "4000:4000"
    depends_on:
      - redis
    networks:
      - bac
    volumes:
      - vol_server:/usr/src/scattegories/
  redis:
    container_name: bac_redis
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - bac

volumes:
  vol_client:
    external: false
  vol_server:
    external: false

networks:
  bac:
    driver: bridge