Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end

  config.vm.define "main" do |main|

    # General
    main.vm.box = "generic/ubuntu2204"
    main.vm.hostname = "server"
    main.vm.synced_folder "../deployment/transfer", "/transfer"
    main.vm.synced_folder "../deployment/keys", "/keys"
  
    # Networking
    main.vm.network "private_network", ip: "192.168.33.223"
    # main.vm.network "public_network", ip: "192.168.33.224"
  
    # Hardware
    main.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    # Provisioning
    main.vm.provision "shell", path: "provisionMain.sh"
  end
end